---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
     cloud: ospcloud
    register: openstack_result
  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
    loop: "{{ openstack_result.openstack_servers }}"
   
