---
# tasks file for lb-tier
- name: install packages needed
  yum:
    name: haproxy
    state: latest
- name: enable HAProxy for use
  service:
    name: haproxy
    state: started
    enabled: yes
- name: configure HAproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy
