- name: install postgres to instance
  yum:
    name: postgresql-server
    state: latest

- name: initilize postgres db if not already
  shell: postgresql-setup initdb
  when: check_db_output.rc != 0

- name: enable postgres 
  service:
    name: postgresql
    enabled: yes
    state: started