---
# tasks file for app-tier
- name: install tomcat
  yum:
    name: tomcat
    state: present

- name: create tomcat root directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy templated index.html to apache root
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  notify: start tomcat

