---
# Initial, common, system setup steps
    
- name: Install EPEL repos 
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present 

- name: Install pip and gcc
  yum:
    name:
      - python-pip
      - gcc
    state: latest

